name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo npm install
      - name: Build
        run: sudo npm run build
      - name: Exclude built files from repository
        run: sudo git update-index --assume-unchanged html.js html.min.js
      - name: Create release artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          paths: |
            html.js
            html.min.js

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Create release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: "Release notes for ${{ github.sha }}"
          draft: false
          prerelease: false
          files: |
            html.js
            html.min.js